version: '3'
services:
  node_1:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - GENESIS=true
    networks:
      - blockchain_net
    container_name: node_1

  node_2:
    build: .
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
    networks:
      - blockchain_net
    container_name: node_2

  node_3:
    build: .
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
    networks:
      - blockchain_net
    container_name: node_3

  node_4:
    build: .
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=production
    networks:
      - blockchain_net
    container_name: node_4

  node_5:
    build: .
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
    networks:
      - blockchain_net
    container_name: node_5

  node_6:
    build: .
    ports:
      - "3006:3000"
    environment:
      - NODE_ENV=production
    networks:
      - blockchain_net
    container_name: node_6

  node_7:
    build: .
    ports:
      - "3007:3000"
    environment:
      - NODE_ENV=production
    networks:
      - blockchain_net
    container_name: node_7


networks:
  blockchain_net:
    driver: bridge